version: '3.4'

services:
  database:
    image: 'postgres:15.3'
    container_name: postgres
    networks:
      - database_net
    env_file:
      - ./configs/variables/dev.env
    volumes:
      - type: bind
        source: ../db-data2/
        target: /var/lib/postgresql/data/
    restart: always
    
  pgadmin:
    image: 'dpage/pgadmin4:7.6'
    container_name: pgadmin
    networks:
      - haproxy_net
      - database_net
    env_file:
      - ./configs/variables/dev.env
    restart: always
    depends_on:
      - database
    volumes:
      - ./configs/pgadmin/:/etc/pgadmin/:ro #config
      - ../pgadmin/:/var/lib/pgadmin/:rw

  redis:
    image: 'redis/redis-stack-server:7.0.6-RC5'
    container_name: redis
    networks:
      - redis_net
    restart: always
    volumes:
      - ../redis_data/:/data

  haproxy:
    container_name: haproxy
    image: haproxy:2.8.1
    volumes:
      - ../passi_cert:/usr/local/etc/haproxy/cert
      - ./configs/haproxy:/usr/local/etc/haproxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - passiwebapi
      - webapp
      - identityserver
    networks:
      - haproxy_net

  webapp:
    image: jetcar/webapp:1.0.10
    networks:
      - haproxy_net
      - database_net
    env_file:
    - ../passi_config/dev.env
    volumes:
      - ../creds:/home/creds
    depends_on:
      - database
    restart: always

  identityserver:
    image: jetcar/identityserver:1.0.10
    networks:
      - haproxy_net
      - database_net
    container_name: identityserver
    env_file:
    - ../passi_config/dev.env
    volumes:
      - ../passi_identity_cert:/myapp/cert
      - ../creds:/home/creds
    depends_on:
      - database
      - passiwebapi
    restart: always

  passiwebapi:
    image: jetcar/passiwebapi:1.0.10
    networks:
      - haproxy_net
      - database_net
      - redis_net
    depends_on:
      - database
      - redis
    env_file:
    - ../passi_config/dev.env
    volumes:
      - ../creds:/home/creds
    restart: always
    
networks:
  haproxy_net:
    driver: bridge

  database_net:
    driver: bridge
    internal: true
    attachable: false
    enable_ipv6: false

  redis_net:
    driver: bridge
    internal: true
    attachable: false
    enable_ipv6: false




