version: '3.4'
services:
  database:
    image: 'postgres:15.5'
    container_name: postgres
    networks:
      - database_net
    env_file:
      - ../passi_config/dev.env
    volumes:
      - type: bind
        source: /mnt/newdisk/db-data3/
        target: /var/lib/postgresql/data/
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  porkbun-ddns:
    image: "mietzen/porkbun-ddns:latest"
    container_name: porkbun-ddns
    env_file:
      - ../passi_config/ddclient.env
    restart: unless-stopped
    networks:
      - haproxy_net
  redis:
    image: 'redis/redis-stack-server:7.0.6-RC5'
    container_name: redis
    networks:
      - redis_net
    restart: always
    volumes:
      - ../redis_data/:/data
  haproxy:
    container_name: haproxy
    image: haproxy:3.1.2
    volumes:
      - ../passi_cert:/usr/local/etc/haproxy/cert
      - ./configs/haproxy:/usr/local/etc/haproxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - passiwebapi
      - webapp
      - mailler-backend
    networks:
      - haproxy_net
  certbot:
    container_name: certbot
    build:
      context: .
      dockerfile: Dockerfile.certbot
    volumes:
      - ../letsencrypt:/etc/letsencrypt
      - ../wwwroot:/var/www/certbot
      - ../passi_cert:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ../passi_config/dev.env
    networks:
      - haproxy_net
    restart: unless-stopped
    depends_on:
      - haproxy
  webapp:
    image: jetcar/webapp:latest
    networks:
      - haproxy_net
      - database_net
    env_file:
      - ../passi_config/dev.env
    volumes:
      - ../creds:/home/creds
      - ../passi_identity_cert:/myapp/cert
      - ../wwwroot/.well-known:/myapp/wwwroot/.well-known
      - ../public:/myapp/wwwroot/public
    depends_on:
      database:
        condition: service_healthy
    restart: always
  openidc:
    image: jetcar/openidc:latest
    networks:
      - haproxy_net
      - database_net
      - redis_net
    container_name: openidc
    env_file:
      - ../passi_config/dev.env
    volumes:
      - ../passi_identity_cert:/myapp/cert
      - ../creds:/home/creds
    depends_on:
      database:
        condition: service_healthy
      passiwebapi:
        condition: service_started
    restart: always
  passiwebapi:
    image: jetcar/passiwebapi:latest
    networks:
      - haproxy_net
      - database_net
      - redis_net
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ../passi_config/dev.env
    volumes:
      - ../creds:/home/creds
      - ../passi_identity_cert:/myapp/cert
    restart: always
  mailler-backend:
    image: jetcar/mailler-backend:latest
    container_name: mailler-backend
    networks:
      - haproxy_net
      - database_net
      - redis_net
    env_file:
      - ../passi_config/mailler.env
    volumes:
      - ../mailler/certs:/certs
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=passi.cloud
      - SERVERPORT=51820
      - PEERS=4
      - PEERDNS=auto
      - INTERNAL_SUBNET=192.168.0.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ../wireguard/config:/config
      - /lib/modules:/lib/modules
    networks:
      - haproxy_net
      - database_net
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
networks:
  haproxy_net:
    driver: bridge
  database_net:
    driver: bridge
    internal: true
    attachable: false
    enable_ipv6: false
  redis_net:
    driver: bridge
    internal: true
    attachable: false
    enable_ipv6: false
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.202.0/24
