version: '3.4'

services:

  database:
    image: 'postgres:13.8'
    container_name: postgres
    networks:
    - dock_net
    env_file:
    - ../passi_config/dev.env
    volumes:
    - ../db-data/:/var/lib/postgresql/data/
    restart: always

  pgadmin:
    image: 'dpage/pgadmin4:6.14'
    container_name: pgadmin
    networks:
    - dock_net
    env_file:
    - ../passi_config/dev.env
    restart: always
    depends_on:
    - database
    volumes:
    - ../passi_config/pgadmin/:/etc/pgadmin/:ro
    - ../pgadmin/:/var/lib/pgadmin/:rw

  redis:
    image: 'redis/redis-stack-server:7.0.6-RC5'
    container_name: redis
    networks:
    - dock_net
    env_file:
    - ../passi_config/dev.env
    restart: always
    volumes:
    - ../redis_data/:/data


  nginx:
    container_name: nginx
    image: nginx:1.23.0
    volumes:
      - ../passi_cert:/etc/cert:ro
      - ./nginx/conf:/etc/nginx:ro
      - ./logs:/logs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
    - webapp
    networks:
      - dock_net

  webapp:
    image: webapp:1.0.4
    networks:
      - dock_net
    env_file:
    - ../passi_config/dev.env
    volumes:
    - ../creds:/home/creds
    depends_on:
    - database
    restart: always


  identityserver:
    image: identityserver:1.0.4
    networks:
      - dock_net
    container_name: identityserver   
    env_file:
    - ../passi_config/dev.env
    volumes:
    - ../creds:/home/creds
    depends_on:
    - database   
    - passiwebapi
    restart: always

  passiwebapi:
    image: passiwebapi:1.0.4
    networks:
      - dock_net
    depends_on:
    - database   
    - redis
    env_file:
    - ../passi_config/dev.env
    volumes:
    - ../creds:/home/creds
    restart: always


  #wireguard:
  #  image: lscr.io/linuxserver/wireguard:latest
  #  container_name: wireguard
  #  cap_add:
  #    - NET_ADMIN
  #    - SYS_MODULE
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=Europe/London
  #    - SERVERURL=passi.cloud #optional
  #    - SERVERPORT=51820 #optional
  #    - PEERS=4 #optional
  #    - PEERDNS=auto #optional
  #    - INTERNAL_SUBNET=10.13.13.0 #optional
  #    - ALLOWEDIPS=0.0.0.0/0 #optional
  #    - LOG_CONFS=true #optional
  #  volumes:
  #    - ../passi_config/vpn_config:/config
  #    - /lib/modules:/lib/modules
  #  ports:
  #    - 51820:51820/udp
  #  sysctls:
  #    - net.ipv4.conf.all.src_valid_mark=1
  #  restart: unless-stopped

networks:
  dock_net:
    driver: bridge




