// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Repos.CompiledModels
{
    [DbContext(typeof(PassiDbContext))]
    public partial class PassiDbContextModel : RuntimeModel
    {
        static PassiDbContextModel()
        {
            var model = new PassiDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static PassiDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
