// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace IdentityServer.CompiledModel
{
    public partial class IdentityDbContextModel
    {
        partial void Initialize()
        {
            var userClient = UserClientEntityType.Create(this);
            var apiResource = ApiResourceEntityType.Create(this);
            var apiResourceClaim = ApiResourceClaimEntityType.Create(this);
            var apiResourceProperty = ApiResourcePropertyEntityType.Create(this);
            var apiResourceScope = ApiResourceScopeEntityType.Create(this);
            var apiResourceSecret = ApiResourceSecretEntityType.Create(this);
            var apiScope = ApiScopeEntityType.Create(this);
            var apiScopeClaim = ApiScopeClaimEntityType.Create(this);
            var apiScopeProperty = ApiScopePropertyEntityType.Create(this);
            var client = ClientEntityType.Create(this);
            var clientClaim = ClientClaimEntityType.Create(this);
            var clientCorsOrigin = ClientCorsOriginEntityType.Create(this);
            var clientGrantType = ClientGrantTypeEntityType.Create(this);
            var clientIdPRestriction = ClientIdPRestrictionEntityType.Create(this);
            var clientPostLogoutRedirectUri = ClientPostLogoutRedirectUriEntityType.Create(this);
            var clientProperty = ClientPropertyEntityType.Create(this);
            var clientRedirectUri = ClientRedirectUriEntityType.Create(this);
            var clientScope = ClientScopeEntityType.Create(this);
            var clientSecret = ClientSecretEntityType.Create(this);
            var deviceFlowCodes = DeviceFlowCodesEntityType.Create(this);
            var identityResource = IdentityResourceEntityType.Create(this);
            var identityResourceClaim = IdentityResourceClaimEntityType.Create(this);
            var identityResourceProperty = IdentityResourcePropertyEntityType.Create(this);
            var persistedGrant = PersistedGrantEntityType.Create(this);
            var dataProtectionKey = DataProtectionKeyEntityType.Create(this);

            UserClientEntityType.CreateForeignKey1(userClient, client);
            ApiResourceClaimEntityType.CreateForeignKey1(apiResourceClaim, apiResource);
            ApiResourcePropertyEntityType.CreateForeignKey1(apiResourceProperty, apiResource);
            ApiResourceScopeEntityType.CreateForeignKey1(apiResourceScope, apiResource);
            ApiResourceSecretEntityType.CreateForeignKey1(apiResourceSecret, apiResource);
            ApiScopeClaimEntityType.CreateForeignKey1(apiScopeClaim, apiScope);
            ApiScopePropertyEntityType.CreateForeignKey1(apiScopeProperty, apiScope);
            ClientClaimEntityType.CreateForeignKey1(clientClaim, client);
            ClientCorsOriginEntityType.CreateForeignKey1(clientCorsOrigin, client);
            ClientGrantTypeEntityType.CreateForeignKey1(clientGrantType, client);
            ClientIdPRestrictionEntityType.CreateForeignKey1(clientIdPRestriction, client);
            ClientPostLogoutRedirectUriEntityType.CreateForeignKey1(clientPostLogoutRedirectUri, client);
            ClientPropertyEntityType.CreateForeignKey1(clientProperty, client);
            ClientRedirectUriEntityType.CreateForeignKey1(clientRedirectUri, client);
            ClientScopeEntityType.CreateForeignKey1(clientScope, client);
            ClientSecretEntityType.CreateForeignKey1(clientSecret, client);
            IdentityResourceClaimEntityType.CreateForeignKey1(identityResourceClaim, identityResource);
            IdentityResourcePropertyEntityType.CreateForeignKey1(identityResourceProperty, identityResource);

            UserClientEntityType.CreateAnnotations(userClient);
            ApiResourceEntityType.CreateAnnotations(apiResource);
            ApiResourceClaimEntityType.CreateAnnotations(apiResourceClaim);
            ApiResourcePropertyEntityType.CreateAnnotations(apiResourceProperty);
            ApiResourceScopeEntityType.CreateAnnotations(apiResourceScope);
            ApiResourceSecretEntityType.CreateAnnotations(apiResourceSecret);
            ApiScopeEntityType.CreateAnnotations(apiScope);
            ApiScopeClaimEntityType.CreateAnnotations(apiScopeClaim);
            ApiScopePropertyEntityType.CreateAnnotations(apiScopeProperty);
            ClientEntityType.CreateAnnotations(client);
            ClientClaimEntityType.CreateAnnotations(clientClaim);
            ClientCorsOriginEntityType.CreateAnnotations(clientCorsOrigin);
            ClientGrantTypeEntityType.CreateAnnotations(clientGrantType);
            ClientIdPRestrictionEntityType.CreateAnnotations(clientIdPRestriction);
            ClientPostLogoutRedirectUriEntityType.CreateAnnotations(clientPostLogoutRedirectUri);
            ClientPropertyEntityType.CreateAnnotations(clientProperty);
            ClientRedirectUriEntityType.CreateAnnotations(clientRedirectUri);
            ClientScopeEntityType.CreateAnnotations(clientScope);
            ClientSecretEntityType.CreateAnnotations(clientSecret);
            DeviceFlowCodesEntityType.CreateAnnotations(deviceFlowCodes);
            IdentityResourceEntityType.CreateAnnotations(identityResource);
            IdentityResourceClaimEntityType.CreateAnnotations(identityResourceClaim);
            IdentityResourcePropertyEntityType.CreateAnnotations(identityResourceProperty);
            PersistedGrantEntityType.CreateAnnotations(persistedGrant);
            DataProtectionKeyEntityType.CreateAnnotations(dataProtectionKey);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.10");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
