// <auto-generated />
using IdentityServer.DbContext;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace IdentityServer.CompiledModel
{
    [DbContext(typeof(IdentityDbContext))]
    public partial class IdentityDbContextModel : RuntimeModel
    {
        static IdentityDbContextModel()
        {
            var model = new IdentityDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static IdentityDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
